### ISSUE TITLE
Missed make after the cmake ..  step

### ISSUE THREAD

**Issue by lethic** [JoakimSoderberg/imageclipper#5]

**Comment by JoakimSoderberg** [comment]
Actually `cmake --build .` works the same as `make` if you use `Makefile` as the CMake generator.

But `cmake --build .` works for all generator types, so it's the same command for both Visual Studio on Windows and Makefiles on Unix.

One benefit of `make` is that you get pretty colors :)

**Comment by lethic** [comment]
Thank you! You instruction helped me a lot.

**Comment by JoakimSoderberg** [comment]
Nice to be of help :)
