### ISSUE TITLE
boost::filesystem::filesystem_error

### ISSUE THREAD

**Issue by joemathai** [JoakimSoderberg/imageclipper#6]
when i try to save the cropped image i get the following error (Ubunutu 14.10)

terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::create_directory: File exists: "./imageclipper"
[3]    13127 abort (core dumped)  ./imageclipper

**Comment by JoakimSoderberg** [comment]
Hello,

Are you running the program from the same directory as your images are in? The default sub-directory `imageclipper` tries to create will be named `path/to/image/files/imageclipper`. So if you already have the executable in that directory named `imageclipper`, it fails to create the directory.

Solution:
1. Run the program from another directory than where you have your images.
2. Change the output format using `-o`

The default output format is:
https://github.com/JoakimSoderberg/imageclipper/blob/master/src/imageclipper.cpp#L127

Use `--help` for more info on the output format.

**Comment by joemathai** [comment]
Thanks @JoakimSoderberg that fixed the issue.
